stages:
  - build

build:
  image: node:20-alpine
  stage: build
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules/
  script:
    - npm ci
    - npm run build
    - npm run test
    - npm run lint